### PR TITLE
Add brute force option to specify IP, Port, & Protocol.

### PR DESCRIPTION
**Pull request by PolyatomicBrian**
I implemented this option as a means of brute forcing a specific target without having to go through the Discovery process. 

This is an excellent addition as users will no longer be required to scan a host prior to attempting the brute force. I often know all the information about my targets beforehand, so it'd be redundant to perform a scan on them.

To access this new feature, go to `2)Attack -> 1)Brute Force -> 3)Attack specific IP, Port, and Protocol`.

The reason the user must specify both a port number and a protocol is simple; a lot of people use certain protocol services on non-standard ports. Perhaps our target is running OpenSSH on Port 2048, then what? Having the user enter this extra info helps improve the accuracy of the attack.

I hope this pull request proves helpful for others!

### CODE REVIEW

**Comment by utkusen** [comment]
oh finally a pull request. thank you for your work. i will check and merge it soon

**Review by utkusen — CHANGES_REQUESTED** [review]
menu banners of the following sections are broken: discovery, brute force, web scanner.

Could you please revert the banner designs?

**Comment by PolyatomicBrian** [comment]
Oof, I did notice that my editor had removed trailing whitespace, but I overlooked whether or not it caused any damage.

I've fixed the banner issues. Sorry about that.
Everything should be good now. 😃

**Comment by utkusen** [comment]
great! thanks for the contribution

**Pull request merged**
